export const SAVE_VERSION = 1;
export const SAVE_KEY = 'mach-vuon.save.v1';
export const MAX_OFFLINE = 8 * 60 * 60 * 1000;
export const WEATHER_PERIOD = 240000;
export const FAMILIES = {
  root: { name: 'Rễ', next: 'leaf', color: '#c87861', icon: 'carrot' },
  leaf: { name: 'Lá', next: 'bloom', color: '#548756', icon: 'leaf' },
  bloom: { name: 'Hoa', next: 'root', color: '#bd9440', icon: 'flower-2' },
};
export const CROPS = {
  radish: {
    name: 'Củ hồng',
    family: 'root',
    level: 1,
    seed: 0,
    time: 24,
    yield: 2,
    value: 3,
    xp: 3,
    color: '#df777e',
    note: 'Nhanh lớn · hạt giống miễn phí',
  },
  mint: {
    name: 'Bạc hà',
    family: 'leaf',
    level: 1,
    seed: 3,
    time: 40,
    yield: 3,
    value: 4,
    xp: 5,
    color: '#6baf7b',
    note: 'Ủ trà · làm thức ăn cho vịt',
  },
  wheat: {
    name: 'Lúa mật',
    family: 'bloom',
    level: 1,
    seed: 5,
    time: 60,
    yield: 3,
    value: 6,
    xp: 7,
    color: '#e1b552',
    note: 'Xay bột · nuôi vịt',
  },
  carrot: {
    name: 'Cà rốt',
    family: 'root',
    level: 3,
    seed: 8,
    time: 85,
    yield: 4,
    value: 7,
    xp: 10,
    color: '#e79453',
    note: 'Sản lượng cao · bánh rau củ',
  },
  blueberry: {
    name: 'Lam quả',
    family: 'leaf',
    level: 4,
    seed: 12,
    time: 110,
    yield: 3,
    value: 13,
    xp: 13,
    color: '#8184b9',
    note: 'Giá trị cao · mứt và trà quả',
  },
  sunflower: {
    name: 'Hướng dương',
    family: 'bloom',
    level: 6,
    seed: 16,
    time: 150,
    yield: 4,
    value: 12,
    xp: 17,
    color: '#e4b748',
    note: 'Ép dầu · giỏ quà bên suối',
  },
};
export const ITEMS = {
  ...Object.fromEntries(
    Object.entries(CROPS).map(([id, c]) => [id, { name: c.name, value: c.value, category: 'crop' }])
  ),
  flour: { name: 'Bột lúa', value: 23, category: 'goods' },
  tea: { name: 'Trà bạc hà', value: 19, category: 'goods' },
  feed: { name: 'Thức ăn vịt', value: 14, category: 'supply' },
  egg: { name: 'Trứng vịt', value: 17, category: 'animal' },
  bread: { name: 'Bánh vườn', value: 61, category: 'goods' },
  jam: { name: 'Mứt lam quả', value: 52, category: 'goods' },
  oil: { name: 'Dầu hoa', value: 47, category: 'goods' },
  berrytea: { name: 'Trà lam sương', value: 61, category: 'goods' },
  basket: { name: 'Giỏ bên suối', value: 165, category: 'goods' },
};
export const BUILDINGS = {
  mill: {
    name: 'Nhà xay gió',
    short: 'Nhà xay',
    level: 1,
    cost: 0,
    icon: 'wind',
    color: '#7b9ca4',
    desc: 'Bột lúa, trà và thức ăn cho vịt.',
  },
  coop: {
    name: 'Nhà vịt',
    short: 'Nhà vịt',
    level: 2,
    cost: 120,
    icon: 'egg',
    color: '#c5976e',
    desc: 'Cho ăn, nhận trứng và thêm một nhịp sống.',
  },
  kitchen: {
    name: 'Bếp bên suối',
    short: 'Bếp vườn',
    level: 3,
    cost: 240,
    icon: 'cooking-pot',
    color: '#c57868',
    desc: 'Bánh vườn và những hũ mứt.',
  },
  press: {
    name: 'Xưởng ép hoa',
    short: 'Xưởng ép',
    level: 6,
    cost: 700,
    icon: 'droplets',
    color: '#9b91ae',
    desc: 'Dầu hoa, trà quả và giỏ quà.',
  },
};
export const RECIPES = {
  flour: { building: 'mill', level: 1, inputs: { wheat: 3 }, output: 'flour', quantity: 1, time: 35, xp: 8 },
  tea: { building: 'mill', level: 1, inputs: { mint: 3 }, output: 'tea', quantity: 1, time: 25, xp: 6 },
  feed: {
    building: 'mill',
    level: 2,
    inputs: { wheat: 1, mint: 1 },
    output: 'feed',
    quantity: 1,
    time: 20,
    xp: 5,
  },
  egg: { building: 'coop', level: 2, inputs: { feed: 1 }, output: 'egg', quantity: 2, time: 65, xp: 10 },
  bread: {
    building: 'kitchen',
    level: 3,
    inputs: { flour: 1, radish: 2, egg: 1 },
    output: 'bread',
    quantity: 1,
    time: 65,
    xp: 18,
  },
  jam: {
    building: 'kitchen',
    level: 4,
    inputs: { blueberry: 3 },
    output: 'jam',
    quantity: 1,
    time: 70,
    xp: 16,
  },
  carrotbread: {
    building: 'kitchen',
    level: 3,
    inputs: { flour: 1, carrot: 2 },
    output: 'bread',
    quantity: 1,
    time: 55,
    xp: 16,
  },
  oil: {
    building: 'press',
    level: 6,
    inputs: { sunflower: 3 },
    output: 'oil',
    quantity: 1,
    time: 80,
    xp: 20,
  },
  berrytea: {
    building: 'press',
    level: 6,
    inputs: { tea: 1, blueberry: 2 },
    output: 'berrytea',
    quantity: 1,
    time: 75,
    xp: 22,
  },
  basket: {
    building: 'press',
    level: 7,
    inputs: { bread: 1, jam: 1, oil: 1 },
    output: 'basket',
    quantity: 1,
    time: 100,
    xp: 35,
  },
};
export const LEVELS = [
  { xp: 0, name: 'Mầm đầu tiên', unlock: 'Củ hồng, bạc hà, lúa mật, nhà xay' },
  { xp: 65, name: 'Góc vườn nhỏ', unlock: 'Nhà vịt · thức ăn vịt' },
  { xp: 180, name: 'Đất lành', unlock: 'Cà rốt · bếp vườn · bờ suối' },
  { xp: 600, name: 'Vườn đơm trái', unlock: 'Lam quả · mứt · tưới lan' },
  { xp: 1400, name: 'Những người bạn', unlock: 'Bãi nắng · hàng đợi mở rộng' },
  { xp: 2800, name: 'Mùa hoa mới', unlock: 'Hướng dương · xưởng ép hoa' },
  { xp: 4700, name: 'Nhịp vườn lớn', unlock: 'Sườn đồi · giỏ bên suối' },
  { xp: 7500, name: 'Một miền xanh', unlock: 'Nhà kính · vườn trọn vẹn' },
];
export const AREAS = {
  creek: {
    name: 'Bờ suối',
    level: 3,
    cost: 260,
    count: 5,
    note: '5 ô đất · mưa tích thêm 2 nước',
    color: '#8fbabe',
  },
  sunny: {
    name: 'Bãi nắng',
    level: 5,
    cost: 680,
    count: 5,
    note: '5 ô đất · cây Hoa lớn nhanh hơn 15%',
    color: '#d8b766',
  },
  hill: {
    name: 'Sườn đồi',
    level: 7,
    cost: 1300,
    count: 6,
    note: '6 ô đất · Rễ luân canh thêm 1 sản lượng',
    color: '#9bac72',
  },
};
export const UPGRADES = {
  storage: {
    name: 'Kho thoáng rộng',
    level: 2,
    cost: 120,
    max: 3,
    multiplier: 2.5,
    icon: 'warehouse',
    note: '+40 chỗ mỗi lần nâng cấp',
  },
  queue: {
    name: 'Bàn soạn mẻ',
    level: 3,
    cost: 180,
    max: 2,
    multiplier: 3,
    icon: 'list-plus',
    note: '+1 chỗ hàng đợi cho mỗi xưởng',
  },
  irrigation: {
    name: 'Rãnh tưới lan',
    level: 4,
    cost: 350,
    max: 1,
    icon: 'droplets',
    note: 'Một lần tưới chạm cả cây cạnh bên',
  },
  greenhouse: {
    name: 'Mái kính đón sương',
    level: 8,
    cost: 1800,
    max: 1,
    icon: 'house',
    note: 'Tưới cây không tốn nước · kho +60',
  },
};
export const WEATHER = [
  {
    id: 'sun',
    name: 'Nắng dịu',
    icon: 'sun',
    color: '#e9ba56',
    desc: 'Cây Hoa lớn nhanh 15%',
    family: 'bloom',
    speed: 0.85,
    demand: 'tea',
  },
  {
    id: 'rain',
    name: 'Mưa ghé vườn',
    icon: 'cloud-rain',
    color: '#77a7b8',
    desc: 'Cây Lá lớn nhanh 15% · nước hồi gấp đôi',
    family: 'leaf',
    speed: 0.85,
    demand: 'flour',
  },
  {
    id: 'breeze',
    name: 'Gió bên suối',
    icon: 'wind',
    color: '#8aaf91',
    desc: 'Cây Rễ lớn nhanh 15%',
    family: 'root',
    speed: 0.85,
    demand: 'egg',
  },
  {
    id: 'gold',
    name: 'Chiều mật ong',
    icon: 'sunset',
    color: '#d59673',
    desc: 'Chợ trả thêm cho bánh và quả',
    family: null,
    speed: 1,
    demand: 'bread',
  },
];
export const PEOPLE = [
  { name: 'An', title: 'Quán trà đầu ngõ', color: '#c78872', portrait: 0 },
  { name: 'Bình', title: 'Chuyến đò buổi sớm', color: '#7c9da5', portrait: 1 },
  { name: 'Miên', title: 'Bếp nhỏ trên đồi', color: '#a39a76', portrait: 2 },
  { name: 'Lâm', title: 'Góc chợ cuối tuần', color: '#9290b0', portrait: 3 },
];
export const QUESTS = [
  {
    title: 'Món quà từ đất',
    text: 'Thu hoạch 3 ô cây đầu tiên.',
    stat: 'harvests',
    target: 3,
    coins: 35,
    xp: 15,
  },
  {
    title: 'Một mạch nối dài',
    text: 'Truyền 3 nhịp sống sang cây cạnh bên.',
    stat: 'pulses',
    target: 3,
    coins: 65,
    xp: 25,
  },
  {
    title: 'Hương trà trong gió',
    text: 'Thu 3 mẻ thành phẩm từ các xưởng.',
    stat: 'products',
    target: 3,
    coins: 80,
    xp: 35,
  },
  {
    title: 'Lời hẹn đầu ngõ',
    text: 'Giao tổng cộng 5 đơn hàng.',
    stat: 'orders',
    target: 5,
    coins: 110,
    xp: 45,
  },
  {
    title: 'Những bước chân bé',
    text: 'Thu 3 mẻ trứng từ nhà vịt.',
    stat: 'eggs',
    target: 3,
    coins: 140,
    xp: 55,
  },
  {
    title: 'Vươn về phía nắng',
    text: 'Mở 2 vùng đất mới.',
    stat: 'expansions',
    target: 2,
    coins: 200,
    xp: 75,
  },
  {
    title: 'Vườn có nhịp riêng',
    text: 'Tạo tổng cộng 80 nhịp sống.',
    stat: 'pulses',
    target: 80,
    coins: 300,
    xp: 100,
  },
  {
    title: 'Một miền xanh',
    text: 'Dựng mái kính đón sương.',
    stat: 'greenhouse',
    target: 1,
    coins: 500,
    xp: 150,
  },
];
export const CATEGORIES = {
  all: 'Tất cả',
  crop: 'Nông sản',
  goods: 'Thành phẩm',
  animal: 'Chăn nuôi',
  supply: 'Vật tư',
};
